FROM --platform=linux/amd64 ubuntu

WORKDIR /usr/project/src

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    gcc \ 
    clang \ 
    valgrind \
    make \
    check \
    clang-format \
    pkg-config \
    sudo \
    git \
    gdb \
    cppcheck \
    clang-tidy \
    gcovr
